Fix to work with latest numpy
The allow_pickle option's default is False since numpy 1.16.3. Fix
by specifying allow_pickle=True explicitly.

Fixes the following crash:

Traceback (most recent call last):
  File "tools/load.py", line 472, in <module>
    scenegraph3d[model]['graph'], scenegraph3d[model]['panoramas'] = load_3DSceneGraph(model, data_path)
  File "tools/load.py", line 199, in load_3DSceneGraph
    building, panoramas = load_file(npz_path, building)
  File "tools/load.py", line 139, in load_file
    data = np.load(npz_path)['output'].item()
  File "python3.7/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "python3.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False